const API_BASE = '/api';
let apiConnected = false;

async function loadSupabaseData() {
	try {
	let payload;
	if (window.sakuraSupabaseClient) {
		const [debtsResult, reimbursementsResult] = await Promise.all([
			window.sakuraSupabaseClient.from('debts').select('id, supplier_id, transaction_date, amount, paid_amount, due_date, note, supplier:suppliers(name)').order('due_date'),
			window.sakuraSupabaseClient.from('reimbursements').select('id, employee_name, expense_date, category, amount, paid_amount, status, note').order('expense_date', { ascending: false })
		]);
		if (debtsResult.error) throw new Error(debtsResult.error.message);
		if (reimbursementsResult.error) throw new Error(reimbursementsResult.error.message);
		payload = { debts: debtsResult.data, reimbursements: reimbursementsResult.data };
	} else if (window.location.protocol !== 'file:') {
		const response = await fetch(`${API_BASE}/dashboard`);
		payload = await response.json();
		if (!response.ok) throw new Error(payload.error || 'Backend Supabase tidak merespons.');
	} else {
		throw new Error('Supabase SDK tidak termuat. Periksa koneksi internet.');
	}

		data.debts = (payload.debts || []).map((item) => ({
			id: item.id,
			supplier: item.supplier?.name || 'Supplier tanpa nama',
			date: item.transaction_date,
			due: item.due_date,
			amount: Number(item.amount),
			paid: Number(item.paid_amount || 0),
			note: item.note || ''
		}));
		data.reimbursements = (payload.reimbursements || []).map((item) => ({
			id: item.id,
			employee: item.employee_name,
			date: item.expense_date,
			category: item.category,
			amount: Number(item.amount),
			paid: Number(item.paid_amount || 0),
			status: item.status,
			note: item.note || ''
		}));
		apiConnected = true;
		save();
		render();
		toast('Terhubung ke Supabase');
	} catch (error) {
		console.error(error);
		toast(`Supabase belum terhubung: ${error.message}`);
	}
}

const key='sakura-event-data';const seed={debts:[{id:'d1',supplier:'PT Gemilang Dekorasi',date:'2026-09-10',due:'2026-09-27',amount:18500000,paid:0,note:'Dekorasi panggung Gala Dinner'},{id:'d2',supplier:'CV Cahaya Sound System',date:'2026-09-05',due:'2026-09-25',amount:8200000,paid:2000000,note:'Sound system acara product launch'},{id:'d3',supplier:'Batik Nusantara',date:'2026-08-29',due:'2026-09-20',amount:6500000,paid:6500000,note:'Seragam crew'}],reimbursements:[{id:'r1',employee:'Nadia Putri',date:'2026-09-18',category:'Transportasi',amount:850000,paid:0,status:'Diajukan',note:'Transport meeting vendor'},{id:'r2',employee:'Raka Pratama',date:'2026-09-15',category:'Perlengkapan',amount:1250000,paid:1250000,status:'Dibayar',note:'Kabel teknis'},{id:'r3',employee:'Sinta Maharani',date:'2026-09-12',category:'Konsumsi',amount:640000,paid:0,status:'Disetujui',note:'Konsumsi rapat'}]};let data=JSON.parse(localStorage.getItem(key)||'null')||seed;const $=id=>document.getElementById(id),rp=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0).replace('Rp','Rp '),left=x=>Math.max(0,x.amount-x.paid),date=x=>new Date(x+'T00:00:00').toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}),sum=a=>a.reduce((s,x)=>s+x.amount,0),save=()=>localStorage.setItem(key,JSON.stringify(data));
function status(x){return `<span class="badge ${x==='Dibayar'||x==='Lunas'?'paid':x==='Disetujui'?'approved':''}">${x}</span>`}function due(x){let d=Math.ceil((new Date(x.due)-new Date('2026-09-24'))/864e5);return d<0?`Lewat ${-d} hari`:d===0?'Hari ini':`${d} hari lagi`}
function render(){let debt=sum(data.debts),reim=sum(data.reimbursements),paid=data.debts.reduce((s,x)=>s+x.paid,0)+data.reimbursements.reduce((s,x)=>s+x.paid,0),open=debt+reim-paid;$('totalDebt').textContent=rp(debt);$('totalReimburse').textContent=rp(reim);$('totalPaid').textContent=rp(paid);$('totalOpen').textContent=rp(open);$('debtBadge').textContent=data.debts.filter(x=>left(x)>0).length;$('reimburseBadge').textContent=data.reimbursements.filter(x=>x.status!=='Dibayar').length;let pct=Math.round(paid/Math.max(debt+reim,1)*100);$('paidPercent').textContent=pct+'%';document.querySelector('.donut').style.background=`conic-gradient(var(--green) ${pct*3.6}deg,#f0f2f3 0deg)`;$('legend').innerHTML=`<div><span><i class="dot"></i>Utang usaha</span><b>${rp(debt)}</b></div><div><span><i class="dot o"></i>Reimbursement</span><b>${rp(reim)}</b></div><div><span><i class="dot g"></i>Sudah dibayar</span><b>${rp(paid)}</b></div>`;let near=data.debts.filter(x=>left(x)>0).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,3);$('deadlines').innerHTML=near.map(x=>`<div class="deadline"><i>!</i><div><b>${x.supplier}</b><small>${x.note}</small></div><div><b>${rp(left(x))}</b><small>${due(x)}</small></div></div>`).join('')||'<p class="empty">Tidak ada kewajiban mendesak.</p>';let recent=[...data.debts.map(x=>({...x,name:x.supplier,type:'Utang',state:left(x)?'Belum Dibayar':'Lunas'})),...data.reimbursements.map(x=>({...x,name:x.employee,type:'Reimbursement',state:x.status}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);$('recent').innerHTML=recent.map(x=>`<tr><td><b>${x.name}</b><small>${x.note||x.category}</small></td><td>${x.type}</td><td>${date(x.date)}</td><td><b>${rp(x.amount)}</b></td><td>${status(x.state)}</td><td><button class="dots" data-menu="${x.type==='Utang'?'debt':'reimburse'}" data-id="${x.id}">•••</button></td></tr>`).join('');renderDebt();renderReimburse();renderReports()}
function renderDebt(){let q=($('debtSearch').value||'').toLowerCase(),f=$('debtFilter').value,list=data.debts.filter(x=>(x.supplier+x.note).toLowerCase().includes(q)&&(f==='all'||f==='open'&&left(x)>0||f==='paid'&&!left(x)));$('debtCount').textContent=data.debts.length+' transaksi';$('debtOpen').textContent=rp(data.debts.reduce((s,x)=>s+left(x),0));$('debtNear').textContent=data.debts.filter(x=>left(x)>0&&Math.ceil((new Date(x.due)-new Date('2026-09-24'))/864e5)<=7).length+' transaksi';$('debtRows').innerHTML=list.map(x=>`<tr><td><b>${x.supplier}</b><small>${x.note}</small></td><td>${date(x.date)}</td><td><b>${date(x.due)}</b><small>${due(x)}</small></td><td><b>${rp(x.amount)}</b></td><td><b>${rp(left(x))}</b></td><td>${status(left(x)?'Belum Dibayar':'Lunas')}</td><td><button class="dots" data-menu="debt" data-id="${x.id}">•••</button></td></tr>`).join('')||'<tr><td colspan="7">Tidak ada data.</td></tr>'}
function renderReimburse(){let q=($('reimburseSearch').value||'').toLowerCase(),f=$('reimburseFilter').value,list=data.reimbursements.filter(x=>(x.employee+x.category).toLowerCase().includes(q)&&(f==='all'||x.status===f));$('reimburseCount').textContent=data.reimbursements.length+' transaksi';$('reimburseOpen').textContent=rp(data.reimbursements.filter(x=>x.status!=='Dibayar').reduce((s,x)=>s+left(x),0));$('reimbursePaid').textContent=rp(data.reimbursements.reduce((s,x)=>s+x.paid,0));$('reimburseRows').innerHTML=list.map(x=>`<tr><td><b>${x.employee}</b><small>${x.note}</small></td><td>${date(x.date)}</td><td>${x.category}</td><td><b>${rp(x.amount)}</b></td><td>${status(x.status)}</td><td><button class="dots" data-menu="reimburse" data-id="${x.id}">•••</button></td></tr>`).join('')||'<tr><td colspan="6">Tidak ada data.</td></tr>'}
function renderReports(){let d=sum(data.debts),r=sum(data.reimbursements),p=data.debts.reduce((s,x)=>s+x.paid,0)+data.reimbursements.reduce((s,x)=>s+x.paid,0);$('reportDebt').textContent=rp(d);$('reportReimburse').textContent=rp(r);$('reportPaid').textContent=rp(p);$('breakdown').innerHTML=[['Utang usaha',d],['Reimbursement',r],['Belum dibayar',d+r-p]].map((x,i)=>`<div class="barline"><span>${x[0]}</span><div class="bar"><i style="width:${x[1]/Math.max(d+r,1)*100}%"></i></div><b>${rp(x[1])}</b></div>`).join('')}
function nav(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('crumb').textContent=page==='debt'?'Utang Usaha':page==='reimburse'?'Reimbursement':page==='reports'?'Laporan':'Dashboard'}
function form(type,item){let debt=type==='debt',edit=!!item;$('modal').innerHTML=`<div class="modal-bg"><div class="modal-box"><div class="modal-head"><h2>${edit?'Edit ': 'Tambah '}${debt?'Utang Usaha':'Reimbursement'}</h2><button class="close">×</button></div><form id="form" class="form">${debt?`<div class="field full"><label>SUPPLIER / VENDOR</label><input name="supplier" required value="${item?.supplier||''}"></div><div class="field"><label>TANGGAL TRANSAKSI</label><input type="date" name="date" required value="${item?.date||'2026-09-24'}"></div><div class="field"><label>JATUH TEMPO</label><input type="date" name="due" required value="${item?.due||''}"></div>`:`<div class="field full"><label>NAMA KARYAWAN</label><input name="employee" required value="${item?.employee||''}"></div><div class="field"><label>TANGGAL PENGELUARAN</label><input type="date" name="date" required value="${item?.date||'2026-09-24'}"></div><div class="field"><label>KATEGORI</label><select name="category"><option>Transportasi</option><option>Perlengkapan</option><option>Konsumsi</option><option>Operasional</option></select></div>`}<div class="field full"><label>NOMINAL</label><input type="number" name="amount" min="0" required value="${item?.amount||''}"></div><div class="field full"><label>KETERANGAN</label><textarea name="note">${item?.note||''}</textarea></div></form><div class="modal-actions"><button class="soft close">Batal</button><button class="primary" id="save">Simpan Transaksi</button></div></div></div>`;document.querySelectorAll('.close').forEach(x=>x.onclick=()=>$('modal').innerHTML='');$('save').onclick=()=>{let o=Object.fromEntries(new FormData($('form')));o.amount=+o.amount;if(edit)Object.assign(item,o);else{Object.assign(o,{id:Date.now().toString(),paid:0});if(debt)data.debts.unshift(o);else Object.assign(o,{status:'Diajukan'}),data.reimbursements.unshift(o)}save();$('modal').innerHTML='';render();toast('Transaksi berhasil disimpan')}}
function menu(type,id){let a=type==='debt'?data.debts:data.reimbursements,x=a.find(y=>y.id===id);$('modal').innerHTML=`<div class="modal-bg"><div class="modal-box"><div class="modal-head"><h2>${type==='debt'?x.supplier:x.employee}</h2><button class="close">×</button></div><div class="form"><button class="soft" data-choice="edit">Edit data</button><button class="soft" data-choice="pay">Catat pembayaran</button><button class="soft" data-choice="delete">Hapus transaksi</button>${type==='reimburse'&&x.status==='Diajukan'?'<button class="soft" data-choice="approve">Setujui pengajuan</button>':''}</div></div></div>`;document.querySelector('.close').onclick=()=>$('modal').innerHTML='';document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{let c=b.dataset.choice;if(c==='edit')form(type,x);if(c==='pay'){let n=+prompt('Nominal pembayaran:',left(x));if(n>0){x.paid=Math.min(x.amount,x.paid+n);if(type==='reimburse'&&x.paid===x.amount)x.status='Dibayar';save();$('modal').innerHTML='';render();toast('Pembayaran berhasil dicatat')}}if(c==='approve'){x.status='Disetujui';save();$('modal').innerHTML='';render();toast('Pengajuan disetujui')}if(c==='delete'&&confirm('Hapus transaksi ini?')){let target=type==='debt'?'debts':'reimbursements';data[target]=a.filter(y=>y.id!==id);save();$('modal').innerHTML='';render();toast('Transaksi dihapus')}})}function toast(t){$('toast').innerHTML=`<div class="toast">${t}</div>`;setTimeout(()=>$('toast').innerHTML='',2600)}
document.addEventListener('click',e=>{let n=e.target.closest('[data-page]'),l=e.target.closest('[data-page-link]'),a=e.target.closest('[data-add]'),m=e.target.closest('[data-menu]');if(n)nav(n.dataset.page);if(l)nav(l.dataset.pageLink);if(a)form(a.dataset.add);if(m)menu(m.dataset.menu,m.dataset.id)});['debtSearch','debtFilter','reimburseSearch','reimburseFilter'].forEach(x=>$(x).addEventListener('input',()=>{renderDebt();renderReimburse()}));$('export').onclick=()=>{let rows=[['Jenis','Nama','Tanggal','Nominal','Dibayar','Sisa','Status'],...data.debts.map(x=>['Utang',x.supplier,x.date,x.amount,x.paid,left(x),left(x)?'Belum Dibayar':'Lunas']),...data.reimbursements.map(x=>['Reimbursement',x.employee,x.date,x.amount,x.paid,left(x),x.status])];let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.map(x=>x.join(',')).join('\n')],{type:'text/csv'}));a.download='laporan-sakura-event.csv';a.click();toast('Laporan berhasil diekspor')};render();